# Python Code generated by Data Analyst
import pandas as pd
import numpy as np
import datetime as dt

# Load the CSV files
# file_path_1996_2014 = '/mnt/data/Munster_Jan1996_December2014.csv'
# file_path_2015_2023 = '/mnt/data/Munster-Jan2015-December-2023.csv'

file_path_1996_2014 = 'C:/Ish/Python/Data/Munster_Jan1996_December2014.csv'
file_path_2015_2023 = 'C:/Ish/Python/Data/Munster-Jan2015-December-2023.csv'

df_1996_2014 = pd.read_csv(file_path_1996_2014)
df_2015_2023 = pd.read_csv(file_path_2015_2023)

# Combine the dataframes
combined_df = pd.concat([df_1996_2014, df_2015_2023], ignore_index=True)

# Selecting the specified columns
columns = ["Street Full Address", "Selling Date", "Selling Price", "Bedrooms", "Total Baths", 
           "Garage # of Cars", "Basement", "Combined SqFt", "Total # of Rooms", "Year Built", 
           "Property Subtype"]
combined_df = combined_df[columns]

# Format the 'Selling Date' column
combined_df['Selling Date'] = pd.to_datetime(combined_df['Selling Date']).dt.strftime('%m/%d/%Y')

# Format 'Selling Price' as U.S. Currency and change type to Numeric
combined_df['Selling Price'] = combined_df['Selling Price'].replace('[\$,]', '', regex=True).astype(float)
combined_df['Selling Price'] = combined_df['Selling Price'].apply(lambda x: "${:,.0f}".format(x))

# Add the new columns 'Year Sold' and 'Days in house'
combined_df['Year Sold'] = pd.to_datetime(combined_df['Selling Date']).dt.year
combined_df['Days in house'] = 0

# Sorting the dataframe
combined_df.sort_values(by=['Street Full Address', 'Selling Date'], key=lambda x: x.str[:10], inplace=True)

# Calculate the average number of houses sold yearly
unique_years = combined_df['Year Sold'].nunique()
total_rows = combined_df.shape[0]
avgHousesSoldYearly = total_rows / unique_years

# Creating the Excel writer with the combined dataframe and 'Myvariables' dataframe
#excel_writer = pd.ExcelWriter('/mnt/data/FileSave1.xlsx', engine='xlsxwriter')
excel_writer = pd.ExcelWriter('C:/Ish/Python/Data/FileSave2.xlsx', engine='xlsxwriter')
combined_df.to_excel(excel_writer, sheet_name='Combined Data', index=False)

# Adding formatting for the new columns
workbook = excel_writer.book
worksheet = excel_writer.sheets['Combined Data']
pink_format = workbook.add_format({'bg_color': '#FFC0CB'})
worksheet.write('L1', 'Year Sold', pink_format)
worksheet.write('M1', 'Days in house', pink_format)

# Creating and writing 'Myvariables' sheet
myvariables_df = pd.DataFrame({'avgHousesSoldYearly': [avgHousesSoldYearly]})
myvariables_df.to_excel(excel_writer, sheet_name='Myvariables', index=False)

# Save and close the Excel file
excel_writer._save()

# Providing the download link
#file_path = '/mnt/data/FileSave1.xlsx'
#file_path
print("******* Done running this .py file  ********")
